"""Add download_count and is_featured to photos only

Revision ID: 2713b11daec1
Revises: 74b622317b8a
Create Date: 2025-08-03 17:51:13.518614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2713b11daec1'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('download_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('photos', sa.Column('is_featured', sa.String(length=5), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'is_featured')
    op.drop_column('photos', 'download_count')
    # ### end Alembic commands ###